main:
  #- name: 关于
    #url: '#about'
    #weight: 1
  #- name: 所有文章
    #url: /posts/
    #weight: 2
  #- name: 文档
    #url: /docs/
    #weight: 3
  - name: 类别
    url: /categories
    weight: 4
  - name: 标签
    url: /tags
    weight: 5
  - name: RSS
    url: /index.xml
    weight: 6
